"""GENERATED by _sync/sync.py — DO NOT EDIT BY HAND.

Real per-trace calcium QC that applies to ANY trace (soma or bouton): SNR (MAD-based noise floor) + A–F grade, and an exponential photobleaching fit (r² gates a spurious decay). Two trace-INTRINSIC failure modes a single SNR cutoff can't both see. (Neuropil contamination is a soma-imaging concern, not applied to boutons; motion/spatial trustworthiness — z-drift, residual xy — lives in the trace-trustworthiness tile.)

These are independent copies of the real lab-pipeline functions, de-identified for
the public gallery. To update: fix the pipeline, then re-run `python _sync/sync.py`.
Provenance (pipeline @ 4ec606b9, synced 2026-08-06):
# lib/core/enums.py :: QualityGrade
# lib/qc/snr_metrics.py :: calculate_snr_per_trace
# lib/qc/photobleaching.py :: fit_exponential_decay
"""
# fmt: off
from __future__ import annotations
from enum import Enum
import numpy as np
from scipy.optimize import curve_fit
MAD_TO_STD = 1.4826 # MAD -> Gaussian sigma (1 / norm.ppf(0.75))


class QualityGrade(str, Enum):
    """Quality grade for ROI/signal assessment."""
    A = "A" # Excellent (>= 0.8)
    B = "B" # Good (>= 0.6)
    C = "C" # Acceptable (>= 0.4)
    D = "D" # Poor (>= 0.2)
    F = "F" # Failed (< 0.2)

    @classmethod
    def from_score(cls, score: float) -> "QualityGrade":
        """Convert quality score (0-1) to grade."""
        if score >= 0.8:
            return cls.A
        elif score >= 0.6:
            return cls.B
        elif score >= 0.4:
            return cls.C
        elif score >= 0.2:
            return cls.D
        return cls.F


def calculate_snr_per_trace(trace: np.ndarray, fs: float = 60.0,
                            baseline_percentile: float = 25.0,
                            signal_percentile: float = 95.0) -> SNRResult:
    """
    Calculate multiple SNR metrics for a single calcium trace.

    Parameters
    ----------
    trace : np.ndarray
        1D array of dF/F or intensity values
    fs : float
        Sampling rate in Hz
    baseline_percentile : float
        Retained for API compatibility; no longer affects the result. The
        baseline/noise are now estimated robustly from the full-trace MAD
        (2026-05-23), which needs no quiet-period percentile. Still validated
        to be in [0, 100].
    signal_percentile : float
        Percentile for signal estimation (default: 95th = peak activity)

    Returns
    -------
    dict
        SNR metrics:
        - snr_peak: (95th percentile - baseline) / baseline_std
        - snr_mean: mean positive signal / baseline_std
        - snr_robust: MAD-based SNR (median absolute deviation)
        - baseline_std: standard deviation of baseline
        - baseline_mean: mean of baseline values
        - signal_amplitude: 95th percentile - baseline
        - noise_floor: estimated noise level (MAD * 1.4826)
        - quality_score: 0-1 score combining multiple metrics

    Raises
    ------
    ValueError
        If fs <= 0 or percentiles are out of range [0, 100]
    """
    # Input validation
    if fs <= 0:
        raise ValueError(f"fs must be positive, got {fs}")
    if not (0 <= baseline_percentile <= 100):
        raise ValueError(f"baseline_percentile must be in [0, 100], got {baseline_percentile}")
    if not (0 <= signal_percentile <= 100):
        raise ValueError(f"signal_percentile must be in [0, 100], got {signal_percentile}")

    trace = np.asarray(trace, dtype=float)
    trace = trace[np.isfinite(trace)]

    if len(trace) < 10:
        return {
            'snr_peak': np.nan, 'snr_mean': np.nan, 'snr_robust': np.nan,
            'baseline_std': np.nan, 'baseline_mean': np.nan,
            'signal_amplitude': np.nan, 'noise_floor': np.nan,
            'quality_score': 0.0
        }

    # Noise estimation: MAD of the FULL trace × MAD_TO_STD (the lab 2026-05-23).
    # The old formula used std of the bottom 25% of the trace, which assumes a
    # lower-envelope baseline (positive-shifted dF/F with noise at the bottom of
    # the distribution). For zero-centered dF/F (median baseline, the current
    # pipeline default) the bottom 25% picks only the LEFT TAIL of symmetric
    # noise → biased noise estimate → biased SNR. MAD of the full trace is robust
    # to sparse signal events, the symmetry assumption (works for both
    # zero-centered and positive-shifted dF/F), and distribution shape.
    median_val = float(np.median(trace))
    mad = float(np.median(np.abs(trace - median_val)))
    noise_floor = mad * MAD_TO_STD # MAD-to-std (Gaussian-equivalent)
    baseline_std = noise_floor # same robust estimate
    # Baseline center: the median (robust center of the noise distribution).
    # Zero-centered dF/F → median ≈ 0; lower-envelope dF/F → median ≈ low value.
    baseline_mean = median_val

    # Signal estimation: upper percentile (peak activity)
    signal_level = np.percentile(trace, signal_percentile)
    signal_amplitude = signal_level - baseline_mean

    # Mean positive signal (above the noise center)
    positive_signal = trace[trace > baseline_mean] - baseline_mean
    mean_positive = np.mean(positive_signal) if len(positive_signal) > 0 else 0

    # SNR calculations — all use the MAD-based noise (any baseline convention)
    snr_peak = signal_amplitude / noise_floor if noise_floor > 1e-6 else np.nan
    snr_mean = mean_positive / noise_floor if noise_floor > 1e-6 else np.nan
    snr_robust = snr_peak # same now; kept for backwards-compat schema

    # Quality score: 0-1 combining multiple factors
    # Good traces have: high SNR, stable baseline, detectable events
    quality_factors = []

    # Factor 1: SNR (0-1, caps at SNR=10)
    if np.isfinite(snr_peak):
        quality_factors.append(min(snr_peak / 10, 1.0))

    # Factor 2: Baseline stability (low std relative to signal)
    if signal_amplitude > 0 and baseline_std > 0:
        stability = 1 - min(baseline_std / signal_amplitude, 1.0)
        quality_factors.append(stability)

    # Factor 3: Dynamic range (signal amplitude should be substantial)
    trace_range = np.percentile(trace, 99) - np.percentile(trace, 1)
    if trace_range > 0:
        dynamic = min(signal_amplitude / trace_range, 1.0)
        quality_factors.append(dynamic)

    quality_score = np.mean(quality_factors) if quality_factors else 0.0

    return {
        'snr_peak': float(snr_peak) if np.isfinite(snr_peak) else np.nan,
        'snr_mean': float(snr_mean) if np.isfinite(snr_mean) else np.nan,
        'snr_robust': float(snr_robust) if np.isfinite(snr_robust) else np.nan,
        'baseline_std': float(baseline_std),
        'baseline_mean': float(baseline_mean),
        'signal_amplitude': float(signal_amplitude),
        'noise_floor': float(noise_floor),
        'quality_score': float(quality_score)
    }


def fit_exponential_decay(trace: np.ndarray, fs: float = 60.0) -> dict:
    """
    Fit exponential decay model to a trace to estimate photobleaching.

    Photobleaching causes slow exponential decay: F(t) = A * exp(-t/tau) + B

    Parameters
    ----------
    trace : np.ndarray
        1D array of fluorescence values (raw or baseline)
    fs : float
        Sampling rate in Hz (default: 60.0)

    Returns
    -------
    dict with keys:
        tau : float
            Decay time constant in seconds (larger = slower decay)
        amplitude : float
            Initial amplitude A
        offset : float
            Asymptotic offset B
        decay_rate : float
            Decay rate per minute (% signal lost per minute)
        r_squared : float
            Goodness of fit (0-1)
        fit_success : bool
            Whether fit converged
    """
    trace = np.asarray(trace, dtype=float)
    n_frames = len(trace)

    if n_frames < 10:
        return {
            'tau': np.nan, 'amplitude': np.nan, 'offset': np.nan,
            'decay_rate': np.nan, 'r_squared': np.nan, 'fit_success': False
        }

    # Create time axis
    t = np.arange(n_frames) / fs

    # Remove NaN values
    valid = ~np.isnan(trace)
    t_valid = t[valid]
    y_valid = trace[valid]

    if len(y_valid) < 10:
        return {
            'tau': np.nan, 'amplitude': np.nan, 'offset': np.nan,
            'decay_rate': np.nan, 'r_squared': np.nan, 'fit_success': False
        }

    # Define exponential decay function
    def exp_decay(t: np.ndarray, A: float, tau: float, B: float) -> np.ndarray:
        """
        Exponential decay model for photobleaching: F(t) = A * exp(-t/tau) + B.

        Parameters
        ----------
        t : np.ndarray
            Time points in seconds
        A : float
            Decay amplitude (initial signal above baseline)
        tau : float
            Decay time constant in seconds (larger = slower decay)
        B : float
            Asymptotic baseline offset

        Returns
        -------
        np.ndarray
            Predicted fluorescence values at each time point
        """
        return A * np.exp(-t / tau) + B

    # Initial parameter estimates
    y_range = y_valid.max() - y_valid.min()
    A0 = y_range * 0.3 # Assume 30% decay
    tau0 = t_valid[-1] / 2 # Half of recording duration
    B0 = y_valid[-1] # Final value as offset

    try:
        # Fit with bounds
        popt, pcov = curve_fit(
            exp_decay, t_valid, y_valid,
            p0=[A0, tau0, B0],
            bounds=([0, 1, 0], [y_valid.max() * 2, t_valid[-1] * 10, y_valid.max()]),
            maxfev=5000
        )

        A, tau, B = popt

        # Calculate R-squared
        y_pred = exp_decay(t_valid, A, tau, B)
        ss_res = np.sum((y_valid - y_pred) ** 2)
        ss_tot = np.sum((y_valid - np.mean(y_valid)) ** 2)
        r_squared = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0

        # Calculate decay rate (% per minute)
        # F(t) = A*exp(-t/tau) + B
        # At t=0: F(0) = A + B
        # At t=60s: F(60) = A*exp(-60/tau) + B
        # Percentage loss = [A*(1 - exp(-60/tau))] / (A + B) * 100
        if tau > 0 and (A + B) > 0:
            decay_per_min = (A * (1 - np.exp(-60 / tau)) / (A + B)) * 100
        else:
            decay_per_min = 0

        return {
            'tau': tau,
            'amplitude': A,
            'offset': B,
            'decay_rate': decay_per_min,
            'r_squared': r_squared,
            'fit_success': True
        }

    except Exception:
        return {
            'tau': np.nan, 'amplitude': np.nan, 'offset': np.nan,
            'decay_rate': np.nan, 'r_squared': np.nan, 'fit_success': False
        }
