"""GENERATED by _sync/sync.py — DO NOT EDIT BY HAND.

Real sub-pixel image registration (register_fov_xy, phase cross-correlation) — reused here to TRACK a bouton's residual xy displacement over time after motion correction. The z-drift detector (resting-F trend vs the FOV) is the tile's own contribution.

These are independent copies of the real lab-pipeline functions, de-identified for
the public gallery. To update: fix the pipeline, then re-run `python _sync/sync.py`.
Provenance (pipeline @ d46072dc, synced 2026-08-29):
# lib/roi/cross_session.py :: _prep_image, _alignment_peak_corr, register_fov_xy
"""
# fmt: off
import numpy as np
from typing import Tuple


def _prep_image(img: np.ndarray) -> np.ndarray:
    """Float, finite, mean-subtracted — the form phase_cross_correlation wants."""
    a = np.asarray(img, dtype=np.float64)
    a = np.nan_to_num(a, nan=0.0, posinf=0.0, neginf=0.0)
    return a - a.mean()


def _alignment_peak_corr(ref: np.ndarray, mov: np.ndarray, dx: float, dy: float) -> float:
    """Normalized cross-correlation between ``ref`` and ``mov`` aligned onto it, given the
    moving→reference displacement ``(dx, dy)`` (SUBTRACT convention). Aligning mov onto ref means
    ndi_shift by ``(-dy, -dx)``. ∈ [0, 1]; ~1 = same FOV, near 0 = different patch."""
    from scipy.ndimage import shift as ndi_shift

    mov_s = ndi_shift(mov, shift=(-dy, -dx), order=1, mode="constant", cval=0.0)
    a, b = ref.ravel(), mov_s.ravel()
    denom = float(np.linalg.norm(a) * np.linalg.norm(b))
    if denom == 0:
        return 0.0
    return float(np.clip(np.dot(a, b) / denom, 0.0, 1.0))


def register_fov_xy(ref_img: np.ndarray, mov_img: np.ndarray,
                    *, upsample_factor: int = 10) -> Tuple[float, float, float]:
    """Sub-pixel (dx, dy) shift mapping ``mov_img`` onto ``ref_img`` + the post-alignment correlation
    peak, via phase cross-correlation. Returns ``(dx, dy, peak_corr)`` with ``peak_corr`` ∈ [0, 1].

    Same engine as the within-session motion correction / consensus shift search; this just runs it
    between two sessions' reference images (mean image, or a structural/STD projection — the more
    stable the reference, the better, since the mean GCaMP image drifts across days)."""
    from skimage.registration import phase_cross_correlation

    ref = _prep_image(ref_img)
    mov = _prep_image(mov_img)
    shift, _error, _phase = phase_cross_correlation(
        ref, mov, upsample_factor=upsample_factor, normalization=None)
    # skimage returns (row=y, col=x) — the shift that ALIGNS moving onto reference (ndi_shift(mov, s)).
    # We return the project SUBTRACT convention instead: the moving→reference DISPLACEMENT
    # (ref_coord = mov_coord − (dx, dy)), which is the NEGATIVE of skimage's align-shift. This is the
    # one that match_boutons_cross_session subtracts — getting this sign right is the whole ball game
    #.
    dy, dx = -float(shift[0]), -float(shift[1])
    peak = _alignment_peak_corr(ref, mov, dx, dy)
    return dx, dy, peak
