#!/usr/bin/env python3
"""Sync gallery tiles from the lab pipeline — extract → de-identify → stamp → write.

The tiles are independent COPIES of real pipeline functions. This script lifts the
manifest's named symbols out of the pipeline source (by AST, so we get exactly the named
defs), de-identifies them (strip recording IDs / personal names / paths — with a fail-loud
guard), stamps a provenance header (source path + pipeline commit + date), and writes the
tile's generated ``_synced.py``. A fix in the pipeline flows one way: fix there → re-run
this → the copy updates, and the change is visible in the tile's git diff.

    python _sync/sync.py                 # regenerate every tile
    python _sync/sync.py --tile dff-baseline
    python _sync/sync.py --check         # verify no drift (exit 1 if out of date) — for CI
    python _sync/sync.py --repo /path/to/pipeline/CalciumPipelineLib
"""
from __future__ import annotations

import argparse
import ast
import datetime as _dt
import os
import subprocess
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
GALLERY_ROOT = _HERE.parent
sys.path.insert(0, str(_HERE))

from deident import NAMES_FILE, assert_clean, deidentify, load_private_names  # noqa: E402
from manifest import PIPELINE_DEFAULT, TILES  # noqa: E402


def _pipeline_commit(repo: Path) -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True)
        return out.stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def _extract_symbols(source_text: str, names: list[str], where: str) -> str:
    """Return the source of the named top-level defs/classes/assignments, in ``names`` order.

    Includes any DECORATORS: ``ast.get_source_segment`` (and node.lineno) start at the
    ``def``/``class`` keyword, dropping decorator lines above — which silently strips e.g.
    ``@dataclass`` and produces a class with no generated ``__init__``. We slice from the first
    decorator's line instead."""
    tree = ast.parse(source_text)
    lines = source_text.splitlines()
    by_name: dict[str, str] = {}
    for node in tree.body:
        node_names: list[str] = []
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            node_names = [node.name]
        elif isinstance(node, ast.Assign):
            node_names = [t.id for t in node.targets if isinstance(t, ast.Name)]
        for nm in node_names:
            if nm in names:
                start = node.lineno
                deco = getattr(node, "decorator_list", [])
                if deco:                                  # keep the @decorator lines above the def/class
                    start = min(d.lineno for d in deco)
                by_name[nm] = "\n".join(lines[start - 1:node.end_lineno])
    missing = [n for n in names if n not in by_name]
    if missing:
        raise SystemExit(f"[sync] {where}: symbol(s) not found: {missing}")
    return "\n\n\n".join(by_name[n] for n in names)


def _render(tile: str, spec: dict, repo: Path, commit: str) -> str:
    date = _dt.date.today().isoformat()
    blocks: list[str] = []
    provenances: list[str] = []
    for rel, names in spec["extracts"]:
        src_path = repo / rel
        if not src_path.exists():
            raise SystemExit(f"[sync] {tile}: source not found: {src_path}")
        body = _extract_symbols(src_path.read_text(), names, f"{tile}:{rel}")
        blocks.append(body)
        provenances.append(f"#   {rel} :: {', '.join(names)}")

    header = (
        f'"""GENERATED by _sync/sync.py — DO NOT EDIT BY HAND.\n\n'
        f"{spec['note']}\n\n"
        f"These are independent copies of the real lab-pipeline functions, de-identified for\n"
        f"the public gallery. To update: fix the pipeline, then re-run `python _sync/sync.py`.\n"
        f"Provenance (pipeline @ {commit}, synced {date}):\n"
        + "\n".join(provenances)
        + '\n"""\n'
        + "# fmt: off\n"
        + spec["header"]
        + "\n\n"
    )
    raw = header + blocks_joined(blocks) + "\n"
    clean = deidentify(raw)
    assert_clean(clean, f"{tile} -> {spec['dest']}")
    return clean


def blocks_joined(blocks: list[str]) -> str:
    return "\n\n\n".join(blocks)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=os.environ.get("PIPELINE_REPO", PIPELINE_DEFAULT),
                    help="path to the pipeline checkout (CalciumPipelineLib)")
    ap.add_argument("--tile", help="only this tile (default: all)")
    ap.add_argument("--check", action="store_true",
                    help="verify tiles are in sync; exit 1 if any is stale (no writes)")
    args = ap.parse_args()

    if not load_private_names():
        print(
            f"[sync] refusing to run: no personal-name list at {NAMES_FILE}.\n"
            f"       Copy _sync/private_names.example.txt to private_names.txt and fill it in —\n"
            f"       without it the de-identifier cannot scrub names and could leak them into a\n"
            f"       public tile.",
            file=sys.stderr,
        )
        return 2
    repo = Path(args.repo).resolve()
    if not repo.exists():
        print(f"[sync] pipeline repo not found: {repo}", file=sys.stderr)
        return 2
    commit = _pipeline_commit(repo)

    tiles = {args.tile: TILES[args.tile]} if args.tile else TILES
    if args.tile and args.tile not in TILES:
        print(f"[sync] unknown tile: {args.tile} (have: {', '.join(TILES)})", file=sys.stderr)
        return 2

    stale, wrote = [], []
    for tile, spec in tiles.items():
        dest = GALLERY_ROOT / "methods" / tile / spec["dest"]
        rendered = _render(tile, spec, repo, commit)
        # Ignore the volatile "synced <date>" line when comparing, so --check reflects real
        # code drift, not the clock.
        def _stable(txt: str) -> str:
            return "\n".join(l for l in txt.splitlines() if not l.startswith("Provenance (pipeline"))
        current = dest.read_text() if dest.exists() else ""
        if args.check:
            if _stable(current) != _stable(rendered):
                stale.append(tile)
            continue
        if _stable(current) != _stable(rendered):
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(rendered)
            wrote.append(tile)
        else:
            print(f"[sync] {tile}: up to date")

    if args.check:
        if stale:
            print("[sync] STALE (re-run `python _sync/sync.py`): " + ", ".join(stale),
                  file=sys.stderr)
            return 1
        print("[sync] all tiles in sync")
        return 0
    for t in wrote:
        print(f"[sync] wrote {TILES[t]['dest']}  (pipeline @ {commit})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
