"""GENERATED by _sync/sync.py — DO NOT EDIT BY HAND.

Real OSI point estimate (direction→orientation folding + negative-response rectification, Mazurek 2014) and the Rayleigh non-uniformity test (n_obs sample size, NOT Kish's n_eff). The population shuffle+FDR call built on these is the tile's own contribution and lives in significance.py, not here.

These are independent copies of the real lab-pipeline functions, de-identified for
the public gallery. To update: fix the pipeline, then re-run `python _sync/sync.py`.
Provenance (pipeline @ d46072dc, synced 2026-08-29):
# lib/analysis/selectivity.py :: calculate_osi, rayleigh_test
"""
# fmt: off
import numpy as np


def calculate_osi(responses: np.ndarray, orientations: np.ndarray,
                  clip_negative: bool = True) -> float:
    """
    Calculate Orientation Selectivity Index (OSI).

    OSI = (R_pref_ori - R_orth_ori) / (R_pref_ori + R_orth_ori)

    Orientations are folded into [0°, 180°) space before comparison:
    responses at θ and θ+180° (same orientation, opposite directions) are
    summed together. This is the correct convention — OSI measures
    orientation tuning independent of direction.

    Reference: Mazurek, Kager & Van Hooser (2014), Front. Neural Circuits,
    DOI:10.3389/fncir.2014.00092. See lib/CITATIONS.md.

    Parameters
    ----------
    responses : np.ndarray
        Mean responses for each direction/orientation
    orientations : np.ndarray
        Direction/orientation values in degrees. If directional (0–360°),
        paired directions (e.g. 0° and 180°) are averaged before computing OSI.

    Returns
    -------
    float
        OSI value between 0 (not selective) and 1 (highly selective)
    """
    if len(responses) < 2 or np.all(np.isnan(responses)):
        return np.nan

    responses = np.asarray(responses, dtype=float)
    valid_mask = ~np.isnan(responses)
    if not np.any(valid_mask):
        return np.nan

    # Rectify negative responses to 0 before folding.
    # On zero-centered dF/F (median baseline) the orthogonal/null response can be
    # negative (noise or active suppression). Without rectification a negative
    # R_orth makes denom = R_pref + R_orth small or ≤ 0 → OSI overshoots (clipped
    # to 1) or returns NaN, systematically dropping the most selective ROIs (those
    # with active suppression). Clipping to 0 keeps OSI well-defined and matches
    # the gOSI/gDSI convention. NaNs are preserved (not rectified to 0).
    if clip_negative:
        responses = np.where(valid_mask, np.maximum(responses, 0.0), responses)

    # Fold directions into orientation space [0°, 180°): sum paired directions
    # e.g. R_ori(0°) = R(0°) + R(180°)
    ori_mod = orientations % 180
    unique_oris = np.unique(ori_mod)
    ori_sum = {}
    for ori in unique_oris:
        paired = (ori_mod == ori) & valid_mask
        if np.any(paired):
            ori_sum[ori] = np.nansum(responses[paired])

    if len(ori_sum) < 2:
        return np.nan

    oris = np.array(list(ori_sum.keys()))
    resps = np.array(list(ori_sum.values()))

    pref_idx = np.argmax(resps)
    pref_ori = oris[pref_idx]
    r_pref = resps[pref_idx]

    # Find orthogonal orientation (90° away in [0°, 180°) space)
    orth_ori = (pref_ori + 90) % 180
    orth_diffs = np.abs(oris - orth_ori)
    orth_diffs = np.minimum(orth_diffs, 180 - orth_diffs)
    orth_idx = np.argmin(orth_diffs)
    r_orth = resps[orth_idx]

    denom = r_pref + r_orth
    if denom <= 0:
        return np.nan

    return np.clip((r_pref - r_orth) / denom, 0, 1)


def rayleigh_test(angles_deg: np.ndarray, weights: np.ndarray = None) -> tuple:
    """
    Rayleigh test for non-uniformity of circular data.

    The weights set the resultant-vector direction and length ``r`` (the
    response profile across orientations), but the **sample size** for the
    z-statistic is the number of sampled directions ``n_obs`` — the count
    of independent stimulus conditions, not a function of the responses.

    Do NOT use Kish's design effect ``n_eff = (Σw)²/Σ(w²)`` here. Kish is
    for survey *sampling* weights; our weights are the *signal* itself, and
    Kish inverts the test's power for tuning: a sharply tuned ROI (weight on
    one orientation) collapses to ``n_eff ≈ 1`` and can never reach
    significance, while the perfectly flat ROI keeps the full ``n``. This
    was the cause of the "0 tuned boutons" regression — every tuned ROI
    scored p ≈ 0.4–0.5 (commit 767c34c, reverted here 2026-06-01). Worked
    example, weights ``[7,2,0,1,1,0,0,1]`` at 8 orientations → p=0.357
    (Kish) vs p=0.023 (n_obs); perfectly tuned ``[7,0,…]`` → p=0.51 vs ~0.

    References
    ----------
    Fisher (1993), *Statistical Analysis of Circular Data*, Cambridge
    Univ. Press, DOI:10.1017/CBO9780511564345 (§4.4, grouped/weighted data).

    Returns
    -------
    tuple
        (z_statistic, p_value)
    """
    n_obs = len(angles_deg)
    if n_obs < 2:
        return np.nan, np.nan

    angles_rad = np.deg2rad(angles_deg)
    if weights is None:
        weights = np.ones(n_obs)

    weights = np.asarray(weights, dtype=float)
    # Rectify negative weights to 0. Circular
    # weights are magnitudes (≥0) by definition; on zero-centered dF/F a response
    # can be negative, and a negative weight would push the resultant vector AWAY
    # from that orientation, distorting r → z → p. preferred_orientation_circular
    # already rectifies — this makes rayleigh_test consistent. NaNs are caller-
    # filtered before this point.
    weights = np.maximum(weights, 0.0)
    w_sum = np.sum(weights)
    if not np.isfinite(w_sum) or w_sum <= 0:
        return np.nan, np.nan

    weights = weights / w_sum
    x = np.sum(weights * np.cos(angles_rad))
    y = np.sum(weights * np.sin(angles_rad))
    r = np.sqrt(x ** 2 + y ** 2)

    # Sample size = number of sampled directions, NOT Kish's n_eff on the
    # response weights (see docstring — Kish inverts power for tuning).
    n = n_obs
    z = n * r ** 2
    p_value = np.exp(-z) * (
        1
        + (2 * z - z ** 2) / (4 * n)
        - (24 * z - 132 * z ** 2 + 76 * z ** 3 - 9 * z ** 4) / (288 * n ** 2)
    )

    return z, np.clip(p_value, 0, 1)
