"""GENERATED by _sync/sync.py — DO NOT EDIT BY HAND.

The event detector and the two noise primitives it rests on: the calmest-window baseline, the negative-tail sigma, the collapsed-denominator guard, and the dF/F-direct detector kept as the comparison arm.

These are independent copies of the real lab-pipeline functions, de-identified for
the public gallery. To update: fix the pipeline, then re-run `python _sync/sync.py`.
Provenance (pipeline @ 27bd6297, synced 2026-09-07):
# lib/events/event_analysis.py :: recovered_f0, bouton_unit_usable, calm_window_baseline, noise_sigma_negative_tail, derive_prominence_k, detect_events_dff, detect_events_arbitrated
"""
# fmt: off
import math
from typing import Optional, Tuple
import numpy as np
from scipy.signal import find_peaks

# module constants the lifted functions default to, with the pipeline's values
MIN_F0_COUNTS = 0.0 # F0 floor for the usability guard; OFF by default
MAX_PLAUSIBLE_DFF = 10.0 # above this a trace is a collapsed denominator


def recovered_f0(intensities: np.ndarray, dff: np.ndarray) -> float:
    """The bouton-unit's own F0 in native counts, recovered as ``median(I) / (1 + median(dF/F))``.

    dF/F is ``(I − F0)/F0`` by construction, so this inverts it exactly. Use it rather than
    ``traces/baselines``: in every master built to date that dataset still carries ``Mean1`` (the
    darkest-patch BACKGROUND ROI) as column 0 while ``groups/<area>/rois/names`` starts at
    ``Mean2``, so ``baselines[j+1]`` is the true F0 of ``names[j]`` and a reader indexing by ROI
    order gets the NEIGHBOUR's F0 (measured on all 45 axon masters 2026-09-01: median relative
    error 0.019 at shift +1 against 0.31 unshifted). ``intensities`` and ``dff`` are correctly
    aligned, so this recovery needs no schema change and no re-run.

    Returns NaN when it cannot be computed.
    """
    i = np.asarray(intensities, float)
    d = np.asarray(dff, float)
    i = i[np.isfinite(i)]
    d = d[np.isfinite(d)]
    if i.size == 0 or d.size == 0:
        return float("nan")
    denom = 1.0 + float(np.median(d))
    if abs(denom) < 1e-9:
        return float("nan")
    return float(np.median(i)) / denom


def bouton_unit_usable(
    reconstructed: np.ndarray,
    measured_dff: np.ndarray,
    intensities: Optional[np.ndarray] = None,
    *,
    min_f0: float = MIN_F0_COUNTS,
    max_dff: float = MAX_PLAUSIBLE_DFF,
) -> tuple:
    """Is this (bouton, unit) measurable at all? Returns ``(ok: bool, reason: str, f0: float)``.

    **The guard is on the RECONSTRUCTED trace being implausible, not on brightness**. She was right on both counts, and the cohort
    says so:

    * **The adaptive bar already handles dim boutons.** Ungated on 102,744 bouton-units, the event
      rate falls MONOTONICALLY with F0 — 0.533/s above 60 counts, 0.433, 0.317, 0.306, 0.225, 0.150,
      0.089, 0.028, **0.022** at F0 1-2. A dim bouton simply never clears its own sigma. A brightness
      filter adds nothing there.
    * **The pathology is confined to F0 < 1 count**, where the rate REVERSES to 2.644/s on a
      reconstruct whose median is 1.2 **million** — the divide-by-nothing regime, in which F0 → 0
      inflates signal and noise together so the ratio can stay above 3. And a reconstruct reaching
      10⁶ is a failure of the reconstruction itself, which is the honest thing to test.
    * **So `max_dff` alone is strictly better than an F0 floor.** `max_dff=10` drops 0.27 % of rows
      and leaves **0** exploding traces; an F0 floor of 5 drops 2.11 % and still leaves 46. Among
      boutons above band-D brightness in their own unit, `rec_med` has a 99.9th percentile of 4.29,
      so a bar at 10 sits 2.3× above the legitimate population and rejects 16 of 48,200 — the broken
      ones.
    * **And the F0 floor destroyed the negative control.** Background-level ROIs are what the
      detector is validated against; an F0 floor of 5 removed **all** of them from the sample
      (2,276 → 0), so the false-positive floor became unmeasurable. Under `max_dff=10` they survive
      (2,046 rows) and their rate reads 0.039/s against 0.542/s for band A — a measured 7 % floor.

    ``min_f0`` therefore defaults to **0 (off)** and is kept only for a caller who explicitly wants a
    brightness floor. Population choice belongs to the analyst — ``per_unit_band_from_companion``
    stratifies by brightness without touching detection.

    A refusal must always be LOUD at the call site: record the reason, never silently count zero
    events, because zero and unusable are different findings — one is a [lab term], the other is a broken
    denominator.
    """
    rec = np.asarray(reconstructed, float)
    dff = np.asarray(measured_dff, float)
    f0 = recovered_f0(intensities, dff) if intensities is not None else float("nan")
    if rec.size == 0 or not np.isfinite(rec).any():
        return False, "reconstructed all-NaN", f0
    if not np.isfinite(dff).any():
        return False, "dff all-NaN", f0
    if float(min_f0) > 0 and intensities is not None and not (np.isfinite(f0) and f0 >= float(min_f0)):
        return False, f"F0 {f0:.2f} < {min_f0} counts (ROI at background level)", f0
    med = float(np.nanmedian(rec))
    if not np.isfinite(med):
        return False, "reconstructed median not finite", f0
    if abs(med) > float(max_dff) or abs(float(np.nanmedian(dff))) > float(max_dff):
        return False, f"median ratio {med:.3g} implausible for dF/F (> {max_dff})", f0
    return True, "", f0


def calm_window_baseline(trace: np.ndarray, fs: float, win_sec: float = 5.0) -> float:
    """The trace's OWN baseline: the mean of its calmest ``win_sec`` window.

    the lab 2026-08-31. The reference level for a height gate must be the
    baseline, NOT the median: the median of an active bouton sits above its baseline by however
    much the bouton fires (measured 0.390 vs 0.131 on a reconstructed trace, and the offset grows
    with activity, Spearman r = +0.33), so a median reference is an *activity-dependent* bar,
    biased against exactly the boutons we are hunting.

    Window selection mirrors :func:`lib.clustering.activity.baseline_stats_5s` — minimal std
    first, lowest mean among the ties. Picking min-mean as primary underestimates a
    photobleaching tail (low mean, high variance).

    Only the mean is returned. The std of a *minimum-std* window is biased low by selection over
    thousands of windows (measured 0.066 against a true σ of 0.198), and detecting with it puts
    36-46 % of events on background-level ROIs — see :func:`detect_events_arbitrated`, which pairs
    this baseline with σ from the measured trace instead.
    """
    x = np.asarray(trace, float)
    x = x[np.isfinite(x)]
    if x.size == 0:
        return float("nan")
    win = int(round(float(win_sec) * float(fs)))
    if win <= 1 or x.size <= win:
        return float(np.mean(x))
    cs = np.cumsum(np.insert(x, 0, 0.0))
    cs2 = np.cumsum(np.insert(x * x, 0, 0.0))
    mean = (cs[win:] - cs[:-win]) / win
    var = (cs2[win:] - cs2[:-win]) / win - mean ** 2
    std = np.sqrt(np.maximum(var, 0.0))
    tied = std <= np.min(std) * 1.05 + 1e-12
    idx = np.flatnonzero(tied)[np.argmin(mean[tied])]
    return float(mean[idx])


def noise_sigma_negative_tail(trace: np.ndarray) -> float:
    """Robust noise σ of a dF/F trace from its below-median (BELOW-baseline) tail only.

    dF/F events are strictly one-sided POSITIVE excursions, so the samples that sit *below the
    baseline* are pure noise by construction — ``σ = sqrt(mean((c[c<med] − med)²))`` needs no
    hand-picked quiet window and is not inflated by a bouton's own activity (Fable red-team
    2026-07-20). Measured about the MEDIAN, not 0: the median-baseline default (q=0.5) has
    med≈0 so this matches the old ``c<0`` form, but on a legacy lower-envelope baseline (q=0.1)
    the trace is NOT zero-centred — med>0 — and measuring about 0 would collapse the tail to a
    few far samples and grossly under- then over-detect (adversarial verify 2026-07-20). Falls
    back to the overall std when there is no usable tail."""
    c = np.asarray(trace, float)
    c = c[np.isfinite(c)]
    if c.size == 0:
        return 0.0
    med = float(np.median(c))
    neg = c[c < med] - med
    if neg.size >= 3:
        return float(np.sqrt(np.mean(neg ** 2)))
    return float(np.std(c))


def derive_prominence_k(min_distance_s: float = 0.12, tau_s: float = 0.4,
                        clip_k: float = 3.0) -> float:
    """The physics-derived prominence bar (in units of σ) — where ``prominence_k=0.78`` comes
    from.

    To resolve two identical events exactly ``min_distance`` apart as TWO peaks, the prominence
    bar must sit below the binding (first) peak's prominence. For an instant-rise / exp-decay(τ)
    kernel the second event fills the first's decaying tail, so that prominence is
    ``(1 − exp(−min_distance/τ))·A``; the weakest event we accept has amplitude ``A = clip_k·σ``
    (it must clear the threshold). Hence the ceiling that still splits the weakest close burst is
    ``(1 − exp(−min_distance/τ))·clip_k`` σ. Defaults → ``(1−exp(−0.3))·3 = 0.777… ≈ 0.78``.
    The shipped ``prominence_k=0.78`` is this value ROUNDED; change dt/τ/
    clip and recompute. Kept as a live, testable function so the derivation is code, not a
    comment on a dead parameter."""
    import math
    return (1.0 - math.exp(-float(min_distance_s) / float(tau_s))) * float(clip_k)


def detect_events_dff(
    dff: np.ndarray,
    fs: float,
    clip_k: float = 3.0,
    prominence_k: float = 0.78,
    min_distance_s: float = 0.12,
    noise: Optional[float] = None,
    return_threshold: bool = False,
):
    """Detect event PEAK FRAMES directly on a dF/F trace. Returns the peak frame indices.

    Rationale (the day's finding): peak detection on the OASIS *deconvolved* trace SMEARS
    bursts — a double/triple burst ([lab term]) collapses into one blob, and deconv isn't even
    sparse (Fable: ~AR(1)-whitened dF/F, so it inflates dust). Detecting on dF/F itself keeps
    the individual burst sub-peaks. Steps:
      1. σ from the below-median tail (:func:`noise_sigma_negative_tail`).
      2. ``find_peaks`` on the raw trace with a **height gate** at ``median + clip_k·σ`` (the — a peak must clear the threshold) and a **prominence
         gate** at ``prominence_k·σ`` measured against the TRUE surrounding valleys, plus
         **distance = round(min_distance_s·fs)** (close burst sub-peaks stay separate).

    **The two gates DON'T ADD (adversarial-verify fix, 2026-07-20).** The earlier version
    *clipped* the trace to the threshold floor BEFORE ``find_peaks``, so prominence was measured
    from that flat floor and the effective height bar silently became ``(clip_k+prominence_k)·σ``
    = 3.78 σ, NOT 3 σ — real 3–3.78 σ events were dropped and [lab term] (the measured variable!)
    over-reported. Passing ``height`` and ``prominence`` as INDEPENDENT ``find_peaks`` conditions
    on the un-clipped trace decouples them: ``height`` does the, ``prominence``
    (from true valleys) rejects decay-tail wiggles, and an isolated 3σ event — prominence ≈ 3σ
    down to the noise floor — passes cleanly.

    **Why prominence_k = 0.78.** The prominence bar must be LOW enough that two identical
    events exactly ``min_distance`` apart are still resolved as two, yet high enough to reject a
    decay-tail wiggle. For an instant-rise / exp-decay(τ) kernel the first (binding) peak's
    prominence against the true valley is ``(1 − exp(−min_distance/τ))·A`` for the weakest
    accepted ``A = clip_k·σ`` — so the ceiling is ``(1 − exp(−0.3))·3 ≈ 0.78 σ``. Derived, not a
    magic number; change min_distance/τ/clip and recompute via ``derive_prominence_k``.

    ``fs`` from MESc metadata — never hardcode (0.12 s = 7 fr @ 61.9 Hz, 4 fr @ 31 Hz). Params
    persist to master provenance so a master self-describes its detector.

    ``return_threshold`` (A2 fix 2026-07-27): also return the actual height gate
    ``thr = median + clip_k·σ`` so the caller can REPORT the detector's real threshold instead
    of a stale MAD number computed on a different trace. Off by default → callers that only
    want peaks are byte-unchanged; a bad/degenerate trace returns ``(empty, nan)``."""
    from scipy.signal import find_peaks
    c = np.asarray(dff, float)
    n = c.shape[0]
    empty = np.array([], dtype=int)
    if n < 3 or not np.isfinite(c).any():
        return (empty, float("nan")) if return_threshold else empty
    sig = noise_sigma_negative_tail(c) if noise is None else float(noise)
    if not np.isfinite(sig) or sig < 1e-9:
        return (empty, float("nan")) if return_threshold else empty
    med = float(np.median(c[np.isfinite(c)]))
    thr = med + float(clip_k) * sig
    cc = np.where(np.isfinite(c), c, med) # NaN-fill to baseline; NO clip (see docstring)
    distance = max(1, int(round(float(min_distance_s) * float(fs))))
    prom = float(prominence_k) * sig if prominence_k and prominence_k > 0 else None
    # height and prominence are INDEPENDENT gates → they do not add: height cuts below-threshold
    # peaks, prominence (from true valleys) rejects decay-tail wiggles.
    pk, _ = find_peaks(cc, height=thr, distance=distance, prominence=prom)
    return (pk.astype(int), float(thr)) if return_threshold else pk.astype(int)


def detect_events_arbitrated(
    reconstructed: np.ndarray,
    measured_dff: np.ndarray,
    fs: float,
    clip_k: float = 3.0,
    prominence_k: float = 0.78,
    min_distance_s: float = 0.12,
    return_threshold: bool = False,
    intensities: Optional[np.ndarray] = None,
    guard: bool = True,
):
    """Detect events on a RECONSTRUCTED trace with the noise scale taken from the MEASURED dF/F.

    ``threshold = calm_window_baseline(reconstructed) + clip_k · noise_sigma_negative_tail(dff)``

    Two corrections to :func:`detect_events_dff`, each arbitrated on real negative controls:

    1. **Reference = the baseline, not the median** — see :func:`calm_window_baseline`.
    2. **σ from the measured dF/F, not from the denoised reconstruct.** A background-level ROI's
       dF/F is violently noisy (it divides by a tiny F₀) while its *reconstruct* is smoothed into
       perfectly plausible "events"; the reconstruct's own σ cannot see that, the measured trace's
       can. Measured σ_dFF/σ_recon = 1.67× for real boutons but **2.90× for background ROIs**, so
       this penalises exactly the traces whose smoothness is an artefact of denoising. The units
       match: both are ÷F₀ ratios, differing only in which baseline was removed (rolling
       quantile vs maximin floor), so σ transfers with no rescaling.

    **Arbitration** (``notes/RESULT_spontaneous_arbitrated_20260831.md``). A phase-randomised
    surrogate is NOT a usable null here — it preserves total power including the energy of the
    real transients, so its own σ is inflated and the same variant scores 1.4 % or 58.8 % false
    positives depending only on whose σ it is handed. The real null is the anatomically REJECTED
    ROIs (``bg_ratio ≤ 1.05``, see
    :func:`lib.analysis.bouton_quality.background_roi_keys_from_companion`): real noise from the
    same recording that cannot host real events. False positives, as a fraction of the bouton
    rate:

    ========================================== ========= ============ ======
    detector boutons/s background/s FP %
    ========================================== ========= ============ ======
    dF/F, median + 3σ (:func:`detect_events_dff`) 0.617 0.642 104.1
    reconstruct, median + 3σ_recon 0.600 0.450 75.0
    reconstruct, baseline + 3σ_recon 0.983 0.800 81.4
    **reconstruct, baseline + 3σ_dFF (this)** 0.608 0.008 1.4
    ========================================== ========= ============ ======

    Also the only variant with a dose-response against anatomical quality (band A 0.650/s →
    D 0.333 → background 0.000), and its events keep 0.63 of their amplitude one τ later, i.e.
    real indicator kinetics.

    **Do NOT put a rolling baseline on a reconstructed trace.** The reconstruct is already built
    maximin-floor ÷F₀, so a rolling quantile on top of it is a *second* baseline subtraction
    (the project rules pitfall #8): the reference rises 0.131 → 0.293 and the rate collapses 0.575 →
    0.183/s for no gain in specificity. A floating baseline is right for dF/F, wrong here.

    Additive: :func:`detect_events_dff` is untouched, so every number produced before this stays
    reproducible. ``fs`` from MESc metadata, never a literal.

    Parameters
    ----------
    reconstructed, measured_dff : np.ndarray
        The same bouton's reconstructed and dF/F traces, same length.
    fs : float
        Per-unit sampling rate from MESc metadata.
    clip_k, prominence_k, min_distance_s
        Height bar in σ, prominence bar in σ (see :func:`derive_prominence_k`), and the minimum
        peak separation that keeps burst sub-peaks separate.
    return_threshold : bool
        Also return the actual height gate, so a caller can report the real threshold.

    Returns
    -------
    np.ndarray of peak frame indices, or ``(peaks, threshold)`` when ``return_threshold``.
    """
    from scipy.signal import find_peaks
    rec = np.asarray(reconstructed, float)
    dff = np.asarray(measured_dff, float)
    empty = np.array([], dtype=int)
    if rec.shape[0] != dff.shape[0]:
        raise ValueError(f"trace length mismatch: reconstructed {rec.shape[0]} vs dff {dff.shape[0]}")
    if rec.shape[0] < 3 or not np.isfinite(rec).any() or not np.isfinite(dff).any():
        return (empty, float("nan")) if return_threshold else empty
    if guard:
        # refuse a degenerate bouton-unit instead of returning hundreds of events from a trace at
        # 1e6 (see bouton_unit_usable). Without `intensities` only the implausible-ratio half of the
        # guard can fire; pass them to get the F0 floor too.
        ok, _why, _f0 = bouton_unit_usable(rec, dff, intensities)
        if not ok:
            return (empty, float("nan")) if return_threshold else empty
    sig = noise_sigma_negative_tail(dff)
    base = calm_window_baseline(rec, fs)
    if not np.isfinite(sig) or sig < 1e-9 or not np.isfinite(base):
        return (empty, float("nan")) if return_threshold else empty
    thr = base + float(clip_k) * sig
    cc = np.where(np.isfinite(rec), rec, base) # NaN-fill to baseline; never nan_to_num to 0
    distance = max(1, int(round(float(min_distance_s) * float(fs))))
    prom = float(prominence_k) * sig if prominence_k and prominence_k > 0 else None
    pk, _ = find_peaks(cc, height=thr, distance=distance, prominence=prom)
    return (pk.astype(int), float(thr)) if return_threshold else pk.astype(int)
