"""GENERATED by _sync/sync.py — DO NOT EDIT BY HAND.

Real cross-session FOV registration: 2-D (register_fov_xy) and full 3-D volume registration (register_zstack_3d) that uses a Sato vesselness fingerprint of the axon arbor rather than the drifting mean image, plus 3-D bouton matching across the recovered shift. All shifts are the project SUBTRACT convention (moving→reference displacement).

These are independent copies of the real lab-pipeline functions, de-identified for
the public gallery. To update: fix the pipeline, then re-run `python _sync/sync.py`.
Provenance (pipeline @ d46072dc, synced 2026-08-29):
# lib/roi/cross_session.py :: CrossSessionFOVResult, _prep_image, _prep_volume, _alignment_peak_corr, _alignment_peak_corr_3d, register_fov_xy, register_zstack_3d, match_boutons_cross_session
"""
# fmt: off
import numpy as np
from dataclasses import dataclass
from typing import List, Optional, Tuple


@dataclass
class CrossSessionFOVResult:
    """Outcome of confirming two sessions image the same FOV + the shift between them.

    Shifts are *moving → reference* (apply to the moving session's coords to land in the reference's),
    following the project's roi_shift convention (SUBTRACT to map moving→reference — see
    `lib/roi/utils`). ``dz_planes`` is in z-stack planes; multiply by the stack's ``z_step_um`` for µm.
    """
    dx: float # x shift (px), moving → reference
    dy: float # y shift (px), moving → reference
    dz_planes: float = 0.0 # z shift (stack planes), moving → reference
    xy_peak_corr: float = 0.0 # normalized cross-correlation peak after xy alignment ∈ [0, 1]
    z_peak_score: Optional[float] = None # best-plane similarity (None until z-registration runs)
    is_same_fov: bool = False # xy_peak_corr ≥ threshold (and z plausible)


def _prep_image(img: np.ndarray) -> np.ndarray:
    """Float, finite, mean-subtracted — the form phase_cross_correlation wants."""
    a = np.asarray(img, dtype=np.float64)
    a = np.nan_to_num(a, nan=0.0, posinf=0.0, neginf=0.0)
    return a - a.mean()


def _prep_volume(vol: np.ndarray, *, enhance: bool = True) -> np.ndarray:
    """Prep a z-stack (z,y,x) for 3-D registration: float, finite, optional vesselness, mean-sub.
    Vesselness locks onto the tubular axon arbor (stable across days) rather than raw brightness."""
    a = np.asarray(vol, dtype=np.float64)
    a = np.nan_to_num(a, nan=0.0, posinf=0.0, neginf=0.0)
    if enhance:
        from skimage.filters import sato
        a = a - a.min()
        a = a / (np.percentile(a, 99.5) + 1e-9)
        a = np.clip(a, 0, 1)
        a = sato(a, sigmas=(1, 2, 3), black_ridges=False)
    return a - a.mean()


def _alignment_peak_corr(ref: np.ndarray, mov: np.ndarray, dx: float, dy: float) -> float:
    """Normalized cross-correlation between ``ref`` and ``mov`` aligned onto it, given the
    moving→reference displacement ``(dx, dy)`` (SUBTRACT convention). Aligning mov onto ref means
    ndi_shift by ``(-dy, -dx)``. ∈ [0, 1]; ~1 = same FOV, near 0 = different patch."""
    from scipy.ndimage import shift as ndi_shift

    mov_s = ndi_shift(mov, shift=(-dy, -dx), order=1, mode="constant", cval=0.0)
    a, b = ref.ravel(), mov_s.ravel()
    denom = float(np.linalg.norm(a) * np.linalg.norm(b))
    if denom == 0:
        return 0.0
    return float(np.clip(np.dot(a, b) / denom, 0.0, 1.0))


def _alignment_peak_corr_3d(ref: np.ndarray, mov: np.ndarray,
                            dz: float, dy: float, dx: float) -> float:
    """Normalized 3-D cross-correlation of ``ref`` vs ``mov`` aligned onto it (moving→reference
    displacement (dz,dy,dx); align = ndi_shift by the negatives). ∈ [0, 1]."""
    from scipy.ndimage import shift as ndi_shift
    mov_s = ndi_shift(mov, shift=(-dz, -dy, -dx), order=1, mode="constant", cval=0.0)
    a, b = ref.ravel(), mov_s.ravel()
    denom = float(np.linalg.norm(a) * np.linalg.norm(b))
    return float(np.clip(np.dot(a, b) / denom, 0.0, 1.0)) if denom else 0.0


def register_fov_xy(ref_img: np.ndarray, mov_img: np.ndarray,
                    *, upsample_factor: int = 10) -> Tuple[float, float, float]:
    """Sub-pixel (dx, dy) shift mapping ``mov_img`` onto ``ref_img`` + the post-alignment correlation
    peak, via phase cross-correlation. Returns ``(dx, dy, peak_corr)`` with ``peak_corr`` ∈ [0, 1].

    Same engine as the within-session motion correction / consensus shift search; this just runs it
    between two sessions' reference images (mean image, or a structural/STD projection — the more
    stable the reference, the better, since the mean GCaMP image drifts across days)."""
    from skimage.registration import phase_cross_correlation

    ref = _prep_image(ref_img)
    mov = _prep_image(mov_img)
    shift, _error, _phase = phase_cross_correlation(
        ref, mov, upsample_factor=upsample_factor, normalization=None)
    # skimage returns (row=y, col=x) — the shift that ALIGNS moving onto reference (ndi_shift(mov, s)).
    # We return the project SUBTRACT convention instead: the moving→reference DISPLACEMENT
    # (ref_coord = mov_coord − (dx, dy)), which is the NEGATIVE of skimage's align-shift. This is the
    # one that match_boutons_cross_session subtracts — getting this sign right is the whole ball game
    #.
    dy, dx = -float(shift[0]), -float(shift[1])
    peak = _alignment_peak_corr(ref, mov, dx, dy)
    return dx, dy, peak


def register_zstack_3d(ref_stack: np.ndarray, mov_stack: np.ndarray, *,
                       upsample_factor: int = 4,
                       enhance: bool = True) -> "CrossSessionFOVResult":
    """Full 3-D registration of two z-stacks → the (dx, dy, dz) shift between sessions, in VOXELS.

    Each a recording session captured a short z-stack of the same FOV (StepZ = -1 µm/plane). Plain mean
    images gave only a weak xy correlation and no z (the cross-session z-jitter that blocks
    bouton-level matching); registering the 3-D VOLUMES recovers all three axes at once. The axon
    arbor is a strong structural fingerprint (far more stable across days than the activity-dependent
    mean), so this is the right anchor.

    ``enhance`` runs a 3-D vesselness (Sato) filter first to lock onto the tubular axon structure
    rather than raw brightness. Returns a :class:`CrossSessionFOVResult` with dx,dy (px),
    ``dz_planes`` (stack planes — multiply by the stack's µm/plane for microns) and the post-alignment
    3-D correlation peak. Sign is the project SUBTRACT convention (moving→reference displacement),
    consistent with :func:`register_fov_xy` and :func:`match_boutons_cross_session`.
    """
    from skimage.registration import phase_cross_correlation

    ref = _prep_volume(ref_stack, enhance=enhance)
    mov = _prep_volume(mov_stack, enhance=enhance)
    # crop both to the common z-depth so the volumes are the same shape (sessions have 22 vs 25 planes)
    nz = min(ref.shape[0], mov.shape[0])
    ny = min(ref.shape[1], mov.shape[1])
    nx = min(ref.shape[2], mov.shape[2])
    ref, mov = ref[:nz, :ny, :nx], mov[:nz, :ny, :nx]

    shift, _err, _phase = phase_cross_correlation(
        ref, mov, upsample_factor=upsample_factor, normalization=None)
    # skimage returns (z, y, x) align-shift; negate for the moving→reference SUBTRACT convention
    dz, dy, dx = -float(shift[0]), -float(shift[1]), -float(shift[2])
    peak = _alignment_peak_corr_3d(ref, mov, dz, dy, dx)
    return CrossSessionFOVResult(dx=dx, dy=dy, dz_planes=dz,
                                 xy_peak_corr=peak, z_peak_score=peak,
                                 is_same_fov=peak >= 0.3)


def match_boutons_cross_session(ref_centroids: np.ndarray, mov_centroids: np.ndarray,
                                shift: CrossSessionFOVResult, *,
                                radius_px: float = 5.0,
                                z_radius_planes: float = 0.0) -> List[Tuple[int, int]]:
    """Match boutons across two sessions given the FOV shift. Returns ``[(ref_i, mov_j), ...]`` pairs.

    ``*_centroids`` are ``(N, 2)`` ``[x, y]`` arrays (the project convention); pass ``(N, 3)`` ``[x, y, z]``
    to match in 3-D. Applies the SUBTRACT convention (moving→reference: ``mov - shift``), then greedily
    pairs each reference bouton to its nearest moving bouton within ``radius_px`` (and ``z_radius_planes``
    in z). Boutons with no partner are dropped — that drop IS the z-jitter cost the consensus measures.
    """
    from scipy.spatial import cKDTree

    ref = np.atleast_2d(np.asarray(ref_centroids, dtype=float))
    mov = np.atleast_2d(np.asarray(mov_centroids, dtype=float)).copy()
    if ref.size == 0 or mov.size == 0:
        return []

    # moving → reference frame: SUBTRACT the shift (see lib/roi/utils convention)
    mov[:, 0] -= shift.dx
    mov[:, 1] -= shift.dy
    if mov.shape[1] >= 3:
        mov[:, 2] -= shift.dz_planes

    # 3-D match if z present: scale z so z_radius_planes maps onto radius_px in the kd-tree metric
    if ref.shape[1] >= 3 and z_radius_planes > 0:
        zscale = radius_px / z_radius_planes
        ref_q = np.column_stack([ref[:, 0], ref[:, 1], ref[:, 2] * zscale])
        mov_q = np.column_stack([mov[:, 0], mov[:, 1], mov[:, 2] * zscale])
    else:
        ref_q, mov_q = ref[:, :2], mov[:, :2]

    tree = cKDTree(mov_q)
    dist, idx = tree.query(ref_q, k=1, distance_upper_bound=radius_px)
    pairs: List[Tuple[int, int]] = []
    used: set = set()
    order = np.argsort(dist) # closest first → greedy 1-to-1
    for ri in order:
        mj = int(idx[ri])
        if not np.isfinite(dist[ri]) or mj in used or mj >= len(mov_q):
            continue
        used.add(mj)
        pairs.append((int(ri), mj))
    return pairs
