"""GENERATED by _sync/sync.py — DO NOT EDIT BY HAND.

Real rolling-quantile baseline (with the auto clamp_below_signal footgun-fix and the light Gaussian post-smooth) and the suite2p maximin FLOOR baseline.

These are independent copies of the real lab-pipeline functions, de-identified for
the public gallery. To update: fix the pipeline, then re-run `python _sync/sync.py`.
Provenance (pipeline @ b1c91757, synced 2026-08-06):
# lib/signals/signal_processing.py :: rolling_baseline, maximin_baseline
"""
# fmt: off
import numpy as np
import pandas as pd
from typing import Optional
from scipy.ndimage import gaussian_filter1d


def rolling_baseline(y: np.ndarray, fps: float = 30.0, win_s: float = 60, q: float = 0.1,
                     smooth_frac: float = 0.05,
                     clamp_below_signal: Optional[bool] = None) -> np.ndarray:
    """
    Robust baseline: rolling q-quantile + light Gaussian smooth.

    Parameters
    ----------
    y : np.ndarray
        1D array of signal values
    fps : float
        Samples per second (default: 30.0)
    win_s : float
        Window length in seconds (drift time-scale, default: 60)
    q : float
        Quantile in [0,1]. 0.1=lower envelope (dF/F noise above 0),
        0.5=median (dF/F noise centered at 0). Default: 0.1.
    smooth_frac : float
        Post-smooth sigma as a fraction of window length (default: 0.05)
    clamp_below_signal : bool, optional
        If True, force baseline ≤ signal (prevents negative dF/F in quiet
        periods) — correct ONLY for lower-envelope baselines. For a median /
        centered baseline (q≈0.5) clamping pulls the baseline DOWN (half the
        samples are below the median), biasing dF/F. If None (default), it is
        auto-derived as ``q < 0.3`` — clamp for lower-envelope, don't for
        centered — so a caller can't accidentally clamp a median baseline
        (the lab 2026-06-03: this was an API footgun; the safe behaviour now
        lives in one place instead of at each call site).

    Returns
    -------
    np.ndarray
        Baseline array with same shape as input
    """
    if clamp_below_signal is None:
        clamp_below_signal = q < 0.3
    y = np.asarray(y, float)
    w = max(5, int(round(win_s * fps)))
    if w % 2 == 0:
        w += 1
    s = pd.Series(y)
    bl = s.rolling(w, center=True, min_periods=1).quantile(q).to_numpy()
    sigma = max(1, int(round(w * smooth_frac)))
    bl = gaussian_filter1d(bl, sigma=sigma, mode='nearest')
    if clamp_below_signal:
        bl = np.minimum(bl, y)
    return bl


def maximin_baseline(y: np.ndarray, fps: float = 60.0, win_s: float = 60.0,
                     sig_frames: float = 10.0) -> np.ndarray:
    """FLOOR baseline via suite2p's maximin: gaussian-smooth → rolling minimum → rolling maximum.

    Unlike the rolling-quantile baseline (which sits at the q-quantile, ~mid-signal for q≈0.3-0.5
    and therefore SUBTRACTS AWAY median-height events), the maximin baseline tracks the true FLOOR
    of the trace — a running minimum envelope, then dilated back by an equal max-filter so it hugs
    the bottom without lagging. Subtracting it keeps median/partial events intact (they carry the
    within-axon propagation signal), matching the suite2p reconstruct that preserves median peaks
    (the lab's finding, a recording 2026-07-23). ``sig_frames`` is the pre-smoothing Gaussian σ in FRAMES;
    ``win_s`` the min/max window in seconds.
    """
    from scipy.ndimage import minimum_filter1d, maximum_filter1d
    y = np.asarray(y, float)
    w = max(5, int(round(win_s * fps)))
    flow = gaussian_filter1d(y, sigma=float(sig_frames), mode='nearest')
    flow = minimum_filter1d(flow, w, mode='nearest')
    flow = maximum_filter1d(flow, w, mode='nearest')
    return flow.astype(np.float32)
